def count_bases(DNA_seq):
    base_count = {'A':0, 'C':0, 'G':0, 'T':0 }
    for letter in DNA_seq:
        for base in base_count:
            if base == letter:
                base_count[base] += 1
    print(base_count)



rosalind = "TCAGCGAAGATATCTCTAGTGAAGTGAGATGAGTTAAAGAAATTGTGAAGCGACCGTAAAACTGGTCAGACTGACGAGGAGTCCCAGGAGTCTTACAGCCAGAAGTAGAGTGTTGGCGAAGTACCTTCAGATAGCCCGCCTTTGAGGGGTTTCCGTGAGAGATTGTGGCTTGCTAGCGTCCTGTGTTCCATAGCTTAGCGACCTATTACTGCGCAGGCGGACCGTTAGGAAGGGGTGGTCGCTTAATTCGCGAAATTATGAACATAGGGTGTCGAACAAAGACCGCCGGTGTTCAACAACGCTAAACTGAATCTAAAGGCGCTCCTCCCGGCAGACTCGTAGGGTAGGAACGAGGTTAAAATGTTTCTGCTTCGCTAAGCTGCGTCCCACACTTGCCTTGCGCAGTTCGGTCGCATCCAACCACGCAGGCGCATGAGACAATGTCGCAAGCCCACGCCGGTACTGTGTGTAGTATGCAGTACTTGCGTTTGATGAGGCGGCACATTGATCGTACTGAAAGAGCTCCAATAAGGTAGCCCAGGCAACGCTTGCGAGAGTTACTTCTAGCGAAAAAACCATATTCGGAAACAGCGTTTTACTAGAAACTCTACCCCGACAAGTATGGCGAAAGGTGCCCGTGATGCGCAGACTCCCGGAGTCTTTTGATGTGTGGAGGAATCGCCCAGTATAGTTATCTGGACCAAACATACGTTACCCGGCTTACTCCTGGCTGCGGGCGGTCCGAGCGGGCCCGCGACTTCAAGTAGAAGCCTTTTAATTTAAGGCCATTAGCGGAAACATTAGCTTCCTTTGATAGAGTAGACCTCGTTTGGGGATTGCCGCAAAAGCTTAGCGACTCTCGGCAGAATCACCTATGATGGTCTC"
count_bases(rosalind)