import sys

data = """ATATCTGTCCCCGTTCGGACCAATCTTTCAGATGAAAAAGGACACTATCTGGAGCGCCGA
AGCAATCCTGTGAATGTGAGTGTCAAGTGTGGCGCTTTAACGAACTAGCGATAGGGAATA
GTATGAGTCCTTCAATTCGCATGCTTGGCACGGTAAAATACCGAGTTCAGACTGTGTACA
GAAATACGAGCACTTAGTATGTATTCGGTCATCATTCGTTTGAATTATATGAAACCGAGT
CGTAGCGCTGAGTACGCGGCTTGAGGCGGCTAGCCGCTATAGCCGCGAACCGCAATCCAT
CGGCAATGCGCGGGCCGTTAACAGTCTGGAGGCCACGACCTATGCTTGACGAGGAGACGT
TGCTAATTTCACATTCTATGGCAGCTTACGTCGTGCTTTACGTGTCTTCCCTCAAGGGAA
ATCCGGGGCATTTTCCATAGGGCAGATCAGCCGATTTTCGGGGGACGTGTACCTAGAGTA
GCTACTCTTGAGATAACCATCCCAATCTGCGTATATCGACCAGTAACCCTTTCACCGGAC
GCCCATAGTAGTAGAGGAACATCGCACCCCATAGGCCATTCCGCATTTCATAATTGCCCC
CAGTACAAGTTCGCTCTTCGTTACTATGGCCTATCGTTACCTAATCAGAACCAGTCGGTG
AGTTTGCCATTGTGCAAGCGCGCGCCGACGAGTCTACGTCTGATCAGACTCAGGACGGGC
CCACAGTAAATTTCTCAAAATCTAGTGAGTGAAAGCGGAACCGCTTCGTAGCTACTGAAA
CTGTCATCTACTAGCCCCCAGCGGAGGGGGAGAGCACCCCTAATGGCCCAGCCGACGACT
ACTGGTTAACAGTCACTAGGGATTGTTGGGACTTTTTGCTTAATAGACCAGTCTTCTATA
GAGCGGTTCCGTACTTTACGACCCGGATGCCCTACTGGTAGGACTTTCACATAATTATCG
CG"""

data = "".join(data.split())
def reverse_complement(strand):
    flips = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
    return "".join([flips[base] for base in strand[::-1]])


results = []

length = len(data)

for a in range(length):
    for b in range(4, 13):

        if a + b > length:
            continue

        strand1 = data[a:a+b]
        strand2 = reverse_complement(strand1)

        if strand1 == strand2:
            results.append((a + 1, b))

for i in range(len(results)):
    results[i] = [str(x) for x in results[i]]
    results[i] = " ".join(results[i])

print("\n".join(results))